Repository BotsBurgh/BOTSBURGH-FTC-2023-24, pull requests merged in 2023-10, with the labels that each got.

#7 Rename motors to use color names
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/TriWheels.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/TeleOpMovement.kt
Labels: breaking

#2 April Tags
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/vision/AprilVision.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/vision/Vision.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/vision/VisionAPI.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/DemoTeleOp.kt
Labels: feature

#9 Set correct angles for wheels
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/TriWheels.kt
Labels: bug

#10 Autonomous Scaffolding
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/API.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/DemoQuadWheels.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/Component.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/DemoForward.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/linear/DemoSpinLinear.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/linear/LinearComponent.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/autonomous/DemoAutonomous.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/DemoTeleOp.kt
Labels: feature, refactor

#8 DPad Commands
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/GamepadEx.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/TeleOpState.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/DPadCommands.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/TeleOpMovement.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/TeleOpMain.kt
Labels: feature

#12 Update to FtcRobotController 9.0.1
  FtcRobotController/src/main/AndroidManifest.xml
  FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/ConceptAprilTag.java
  FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/ConceptAprilTagEasy.java
  FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/ConceptTensorFlowObjectDetection.java
  FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/RobotAutoDriveToAprilTagOmni.java
  FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/RobotAutoDriveToAprilTagTank.java
  build.dependencies.gradle
Labels: chore

#13 Fix teleop driving angle
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/TeleOpMovement.kt
Labels: bug

#16 TriWheels Changes
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/TriWheels.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/TeleOpMovement.kt
Labels: refactor

#14 Resettable APIs and Components
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/API.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/GamepadEx.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/TeleOpState.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/DPadCommands.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/autonomous/DemoAutonomous.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/DemoTeleOp.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/TeleOpMain.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/Reset.kt
Labels: bug, breaking

#18 Teleop slow movement
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/TeleOpMovement.kt
Labels: feature

#19 Autonomous cherry pick
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/linear/LinearAPI.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/linear/DemoSpinLinear.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/linear/LinearComponent.kt
Labels: breaking, chore
