Repository BotsBurgh/BOTSBURGH-FTC-2023-24, pull requests merged in 2023-11, with the labels that each got.

#17 Encoder movement
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/TriWheels.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/linear/Encoders.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/Telemetry.kt
Labels: feature

#21 Telemetry API
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Telemetry.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/Telemetry.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/autonomous/DemoAutonomous.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/DemoTeleOp.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/TeleOpMain.kt
Labels: feature

#25 Fix webcam name
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/vision/Vision.kt
Labels: bug

#24 Robot Config
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Telemetry.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/linear/Encoders.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/RobotConfig.kt
Labels: refactor

#28 Deposit pixel on backdrop during autonomous
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/linear/AprilMovement.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/vision/AprilVision.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/vision/Vision.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/RobotConfig.kt
  TeamCode/src/main/java/org/firstinspires/ftc/vision/VisionPortalHacks.kt
Labels: feature

#31 Debug Toggle Configurations
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Telemetry.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/vision/Vision.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/RobotConfig.kt
Labels: feature
