Repository BotsBurgh/BOTSBURGH-FTC-2023-24, pull requests merged in 2023-12, with the labels that each got.

#33 Cherry-pick red green changes
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/linear/Encoders.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/TeleOpMovement.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/autonomous/AutoForward.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/autonomous/AutoMain.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/RobotConfig.kt
Labels: chore

#37 remove robot state
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/TeleOpState.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/DPadCommands.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/TeleOpMovement.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/TeleOpMain.kt
Labels: chore

#39 Small changes
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/TriWheels.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/vision/Vision.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/vision/VisionAPI.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/RobotConfig.kt
Labels: refactor, chore

#41 Status LED API
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/StatusLed.kt
Labels: feature

#46 Reset listener
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/autonomous/AutoForward.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/autonomous/AutoMain.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/autonomous/DemoAutonomous.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/DemoTeleOp.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/TeleOpMain.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/Reset.kt
Labels: feature
