Repository BotsBurgh/BOTSBURGH-FTC-2023-24, pull requests merged in 2024-01, with the labels that each got.

#47 constants to RobotConfig
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/TeleOpMovement.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/RobotConfig.kt
Labels: refactor

#36 Box Movement
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Box.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/TeleOpMovement.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/TeleOpMain.kt
Labels: feature

#48 Remove components
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/Component.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/DemoForward.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/TeleOpMovement.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/linear/DemoSpinLinear.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/components/linear/LinearComponent.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/TeleOpMain.kt
Labels: refactor, breaking

#49 Drone API
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Drone.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/autonomous/AutoMain.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/TeleOpMain.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/RobotConfig.kt
Labels: feature

#51 Cleanup Code
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/API.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Box.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/DemoQuadWheels.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/TriWheels.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/autonomous/AutoMain.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/autonomous/DemoAutonomous.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/autonomous/JankAuto.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/DemoTeleOp.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/TeleOpMain.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: chore

#53 Clean up RobotConfig
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/TeleOpMain.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/RobotConfig.kt
Labels: chore

#52 API Dependencies
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/API.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/linear/AprilMovement.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/linear/Encoders.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/linear/LinearAPI.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/vision/AprilVision.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/APIDependencies.kt
Labels: feature, breaking

#54 Cube Scanning
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/vision/CubeVision.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/vision/Vision.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/RobotConfig.kt
Labels: feature
